#ifndef SRC_RESOURCES_INTERRUPTS_INTERRUPTCONFIGURATION_H_
#define SRC_RESOURCES_INTERRUPTS_INTERRUPTCONFIGURATION_H_

//_____________________________________________
//TYPES:

//Types of ISR-Routine-Implementations
#define NONE 0
#define BLOCK 1
#define NOBLOCK 2

//_____________________________________________
//CONFIGURATION:

//Implementation Type configuration for each Interrupt source [NONE / BLOCK / NOBLOCK]
#define ISRTYPE_USART0_RX BLOCK
#define ISRTYPE_USART0_TX BLOCK
#define ISRTYPE_USART0_UDRE BLOCK
#define ISRTYPE_USART1_RX NONE
#define ISRTYPE_USART1_TX NONE
#define ISRTYPE_USART1_UDRE NONE
#define ISRTYPE_USART2_RX NONE
#define ISRTYPE_USART2_TX NONE
#define ISRTYPE_USART2_UDRE NONE
#define ISRTYPE_USART3_RX NONE
#define ISRTYPE_USART3_TX NONE
#define ISRTYPE_USART3_UDRE NONE


#endif /* SRC_RESOURCES_INTERRUPTS_INTERRUPTCONFIGURATION_H_ */
